[package]
name = "rust-uniswap-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
futures = "0.3"
tokio = "1.21"
hex = "0.4"
web3 = "0.19"
dotenv = "0.15"
